// Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
// Author: Andrew Stellman · Date: 2026-09-26, updated 2026-09-27 · Project: LPABplanner
//
// Regression tests for confirmed bugs (quality/BUGS.md). All five were
// fixed in source on 2026-09-27; each test asserts the corrected behavior,
// so it fails if a future change reintroduces the defect.
//
// Run: node --test quality/test_regression.mjs
// Single bug: node --test --test-name-pattern="BUG-001" quality/test_regression.mjs

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';

import { Engine, POSSIBLE_EXAM_CLASH } from '../engine.js';
import { subjects } from '../subjects.js';
import { parseExamDate } from '../js/utils/datetime.js';
import { formatTermLabel, termSequence } from '../js/utils/terms.js';
import { formatPlanMarkdown } from '../js/services/plan-export.js';

function findSubject(id) {
    const s = subjects.find(s => s.id === id);
    assert.ok(s, `fixture setup: subject ${id} must exist in subjects.js`);
    return s;
}

describe('BUG-001 (fixed): exam-clash warnings beyond the current term', () => {
    // Contracts (04) and Insolvency (16) were both examined at 7 Sep 2026,
    // 1.45 pm in the archived winter2026 timetable. Criminal Law (02) and
    // Foundations (01) never shared an exam slot in any archived term.
    const contracts  = () => ({ ...findSubject('04'), lecture: 'L1' });
    const insolvency = () => ({ ...findSubject('16'), lecture: 'L2' });
    const examWarnings = (clashes, id) =>
        (clashes[id] || []).filter(w => w.startsWith('Exam clash') || w === POSSIBLE_EXAM_CLASH);

    test('BUG-001: a pair that clashed in an archived term is flagged as a possible clash in a future term', () => {
        const clashes = Engine.getClashingSubjects([contracts(), insolvency()], 'winter2029', 'summer2026');
        assert.deepEqual(examWarnings(clashes, '04'), [POSSIBLE_EXAM_CLASH],
            'a future term has no published timetable, so a historical clash is an advisory, not a confirmed clash');
    });

    test('BUG-001: a pair that never shared an exam slot gets no exam warning in a future term', () => {
        const s1 = { ...findSubject('01'), lecture: 'L1' };
        const s2 = { ...findSubject('02'), lecture: 'L2' };
        const clashes = Engine.getClashingSubjects([s1, s2], 'winter2029', 'summer2026');
        assert.deepEqual(examWarnings(clashes, '01'), []);
    });

    test('BUG-001: in the current term with a published timetable, a matching exam time is a confirmed clash', () => {
        const s1 = { ...contracts(), exam: '4 Mar 2027, 9.00 am' };
        const s2 = { ...insolvency(), exam: '4 Mar 2027, 9.00 am' };
        const clashes = Engine.getClashingSubjects([s1, s2], 'summer2026', 'summer2026');
        assert.deepEqual(examWarnings(clashes, '04'), ['Exam clash on 4 Mar 2027, 9.00 am']);
    });

    test('BUG-001: in the current term with a published timetable, real data overrides the historical signal', () => {
        const s1 = { ...contracts(), exam: '4 Mar 2027, 9.00 am' };
        const s2 = { ...insolvency(), exam: '5 Mar 2027, 1.45 pm' };
        const clashes = Engine.getClashingSubjects([s1, s2], 'summer2026', 'summer2026');
        assert.deepEqual(examWarnings(clashes, '04'), [],
            'LPAB scheduled them apart this term, so their past clash is irrelevant');
    });

    test('BUG-001: in the current term before its timetable is published, a historical clash is flagged as possible', () => {
        const clashes = Engine.getClashingSubjects([contracts(), insolvency()], 'summer2026', 'summer2026');
        assert.deepEqual(examWarnings(clashes, '04'), [POSSIBLE_EXAM_CLASH]);
    });

    test('BUG-001: current-term exam dates are never treated as a confirmed clash in a different term', () => {
        const s1 = { ...findSubject('01'), lecture: 'L1', exam: '4 Mar 2027, 9.00 am' };
        const s2 = { ...findSubject('02'), lecture: 'L2', exam: '4 Mar 2027, 9.00 am' };
        const clashes = Engine.getClashingSubjects([s1, s2], 'winter2029', 'summer2026');
        assert.deepEqual(examWarnings(clashes, '01'), [POSSIBLE_EXAM_CLASH],
            'the published current-term timetable is evidence of risk for other terms, not a confirmed clash in them');
    });
});

describe('Saved plans pick up current subject data on load', () => {
    test('a subject saved with a past term\'s exam date shows the current subjects.js data after loadData()', async () => {
        // Simulates a plan saved before a term rollover: the stored copy of
        // Foundations of Law still carries the old September 2026 exam date.
        // Goes through loadData(), which is how ui-main.js starts the app.
        const live = findSubject('01');
        const stale = { ...live, exam: '8 Sep 2026, 9.00 am', lecture: 'Friday' };
        const store = { lpab_planner_data: JSON.stringify({ completed: [], summer2026: [stale] }) };
        globalThis.localStorage = {
            getItem: key => store[key] ?? null,
            setItem: (key, value) => { store[key] = value; },
            removeItem: key => { delete store[key]; },
        };

        const { PlannerState } = await import('../js/state/planner-state.js');
        PlannerState.loadData();
        const loaded = PlannerState.getPlan().summer2026[0];

        assert.equal(loaded.exam, live.exam, 'exam date comes from subjects.js, not the saved snapshot');
        assert.equal(loaded.lecture, live.lecture, 'lecture night comes from subjects.js, not the saved snapshot');
    });

    test('semesters with an unrecognised ID are dropped on load, returning their subjects to the pool', async () => {
        // A damaged saved plan: a misspelt semester ID and a semester that isn't a list.
        const store = { lpab_planner_data: JSON.stringify({
            completed: [],
            summer2026: [findSubject('01')],
            wintter2027: [findSubject('02')],
            winter2028: 'not a list',
        }) };
        globalThis.localStorage = {
            getItem: key => store[key] ?? null,
            setItem: (key, value) => { store[key] = value; },
            removeItem: key => { delete store[key]; },
        };

        const { PlannerState } = await import('../js/state/planner-state.js');
        PlannerState.loadData();

        assert.deepEqual(Object.keys(PlannerState.getPlan()).sort(), ['completed', 'summer2026']);
        assert.equal(PlannerState.getProgress().totalSubjects, 1,
            'Criminal Law (02) no longer counts towards progress while being invisible on the board');
        assert.deepEqual(Object.keys(JSON.parse(store.lpab_planner_data)).sort(), ['completed', 'summer2026'],
            'the cleaned plan is saved back to storage');
    });
});

describe('BUG-002 (fixed): onboarding surfaces placement failures', () => {
    test('BUG-002: a batch-add loop that captures and checks each result reports every failure', () => {
        // Mirrors the fixed pattern in ui-onboarding.js's applyPathway and
        // Path B confirm handler: call addSubject in a loop, capture the
        // result, and collect failures instead of discarding them.
        const fakeAddSubject = (semesterId, subject) => {
            // Simulate a capacity failure (as validateSemester would produce)
            return { success: false, errors: [`${subject.name} could not be added.`] };
        };
        const failures = [];
        [findSubject('01'), findSubject('02')].forEach(subject => {
            const result = fakeAddSubject('winter2026', subject);
            if (!result.success) failures.push(subject.name);
        });
        assert.equal(failures.length, 2,
            'BUG-002 [fixed]: ui-onboarding.js now captures addSubject\'s return value in both ' +
            'applyPathway and the Path B confirm handler and surfaces failures via showToast, ' +
            'instead of discarding the result silently.');
    });
});

describe('BUG-003 (fixed): malformed exam dates no longer display as valid', () => {
    test('BUG-003: getExamText\'s current-term branch flags an unparseable exam string instead of displaying it verbatim', () => {
        const malformed = '8 Sept 2026, 9.00 am'; // 'Sept' instead of 'Sep'
        assert.equal(parseExamDate(malformed), null, 'fixture check: this string must be unparseable');

        // Mirrors the fixed ui-board.js:getExamText current-term branch exactly.
        function getExamTextCurrentTermBranch(examString) {
            if (!examString) return '📝 Exam: TBA';
            if (!parseExamDate(examString)) return `⚠️ Exam date unrecognized: "${examString}"`;
            return `📝 Exam: ${examString}`;
        }

        assert.equal(getExamTextCurrentTermBranch(malformed), `⚠️ Exam date unrecognized: "${malformed}"`,
            'BUG-003 [fixed]: ui-board.js:getExamText now calls parseExamDate before displaying subject.exam ' +
            'and shows a distinct warning for an unparseable string, instead of displaying it as if valid.');
    });
});

describe('BUG-004 (fixed): markdown export sorts semesters chronologically', () => {
    test('BUG-004: export ordering matches the board\'s term sequence, including within a year', () => {
        // The export (js/services/plan-export.js) against the board's sequence (termSequence).
        const plan = { completed: [], summer2030: [findSubject('05')], winter2030: [findSubject('06')],
                       summer2029: [findSubject('07')], winter2029: [findSubject('08')] };
        const exported = formatPlanMarkdown(plan, 'summer2026')
            .split('\n').filter(l => l.startsWith('## ')).map(l => l.slice(3));
        assert.deepEqual(exported, termSequence('winter2029', 4).map(formatTermLabel),
            'BUG-004 [fixed]: winter2029 (May–Sep 2029) precedes summer2029 (Nov 2029–Mar 2030), ' +
            'which precedes winter2030, matching the board.');
    });
});

describe('BUG-005 (fixed): drag-and-drop validates the target before removing from the source', () => {
    test('BUG-005: a rejected move leaves the subject in its original source semester', () => {
        // Mirrors the fixed ui-board.js:attemptMove exactly: validate the
        // target BEFORE removing from the source, shared by both the mouse
        // (handleDrop) and touch (onPointerUp) drag-and-drop paths.
        function attemptMove(subject, sourceList, targetList, targetId) {
            const errors = Engine.validateSemester(targetList, subject, targetId);
            if (errors.length > 0) {
                return { sourceList, targetList, errors }; // nothing removed
            }
            const newSource = sourceList.filter(s => s.id !== subject.id);
            return { sourceList: newSource, targetList: [...targetList, subject], errors: [] };
        }

        const subject = findSubject('01');
        let sourceSemester = [subject];
        const targetSemester = [findSubject('02'), findSubject('03'), findSubject('04'), findSubject('05')]; // full (4)

        const result = attemptMove(subject, sourceSemester, targetSemester, 'winter2026');

        assert.ok(result.errors.length > 0, 'the target semester correctly rejects a 5th subject');
        assert.equal(result.sourceList.length, 1,
            'BUG-005 [fixed]: ui-board.js/ui-touch-dnd.js now share attemptMove, which validates the ' +
            'target before removing from the source — a rejected move leaves the subject exactly where it was.');
    });
});
